runtime: go112
main: ./cmd/outlived

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/.*
- url: /task
  script: auto
  secure: always
- url: /.*
  script: auto
  secure: always
