runtime: go123
main: ./cmd/outlived

handlers:
- url: /r
  script: auto
  secure: always
- url: /s/.*
  script: auto
  secure: always
- url: /t/.*
  script: auto
  secure: always
- url: /(..*)
  static_files: web/public/\1
  upload: web/public/.*
  secure: always
- url: /
  static_files: web/public/index.html
  upload: web/public/index.html
  secure: always
