package site

import (
	"html/template"
	"net/http"

	"github.com/bobg/aesite"
	"github.com/pkg/errors"

	"github.com/bobg/outlived"
)

func (s *Server) handleHome(w http.ResponseWriter, req *http.Request) error {
	ctx := req.Context()
	sess, err := aesite.GetSession(ctx, s.dsClient, req)
	if err != nil {
		return errors.Wrap(err, "getting session")
	}

	var dict map[string]interface{}

	if sess != nil {
		u := new(outlived.User)
		err = s.dsClient.Get(ctx, sess.UserKey, u)
		if err != nil {
			return errors.Wrap(err, "getting user")
		}

		csrf, err := sess.CSRFToken()
		if err != nil {
			return errors.Wrap(err, "setting CSRF token")
		}
		dict = map[string]interface{}{
			"user": u,
			"csrf": csrf,
		}
	}

	tmpl, err := template.New("").Parse(homeTmpl)
	if err != nil {
		return errors.Wrap(err, "parsing HTML template")
	}

	err = tmpl.Execute(w, dict)
	return errors.Wrap(err, "executing HTML template")
}

const homeTmpl = `
<html>
  <head>
    <title>
      Outlived
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/css/datepicker.min.css"></link>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Livvic:500i&display=swap">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="/static/js/datepicker.min.js"></script>
    <script src="/static/js/datepicker.en.js"></script>
    <script src="/static/js/home.js"></script>
    <style>
      /* CSS - Cascading Style Sheet */
      /* Palette color codes */
      /* Palette URL: http://paletton.com/#uid=53a0k0kllllKW80tkeFdms05nD0 */

      /* As hex codes */

      .color-primary-0 { color: #256F5C }	/* Main Primary color */
      .color-primary-1 { color: #00291F }
      .color-primary-2 { color: #064C3B }
      .color-primary-3 { color: #559182 }
      .color-primary-4 { color: #9DBCB4 }

      .color-secondary-1-0 { color: #28536C }	/* Main Secondary color (1) */
      .color-secondary-1-1 { color: #011A29 }
      .color-secondary-1-2 { color: #0A334A }
      .color-secondary-1-3 { color: #56798E }
      .color-secondary-1-4 { color: #9CAFBA }

      .color-secondary-2-0 { color: #2C8437 }	/* Main Secondary color (2) */
      .color-secondary-2-1 { color: #003106 }
      .color-secondary-2-2 { color: #085B12 }
      .color-secondary-2-3 { color: #65AD6E }
      .color-secondary-2-4 { color: #B1D4B5 }

      /* Generated by Paletton.com © 2002-2014 */
      /* http://paletton.com */

      h1 {
          font-family: 'Livvic', sans-serif;
      }
      body {
          background-color: #9DBCB4;
          color: #28536C;
      }
      img.img64 {
          max-width: 64px;
          height: auto;
      }
      ul.grid {
          margin: 0 auto;
          text-align: center;
          display: grid;
          grid-template-columns: repeat(auto-fill, 20em);
      }
      ul.grid li {
          display: inline-block;
          vertical-align: top;
          margin: 1em 2em;
      }
    </style>
  </head>
  <body>
    <h1>Outlived</h1>

    {{ if .user }}

      <div id="account-div">
        <form method="POST" action="/logout">
          Signed in as {{ .user.Email }}
          <button type="submit">Logout</button>
          <input type="hidden" name="csrf" value="{{ .csrf }}"></input>
        </form>
      </div>

      <div id="settings">
        <label for="active">Receive outlived e-mail?</label>
        <input type="checkbox"
               id="active" 
               name="active" 
               {{ if .user.Active }} checked {{ end }} 
               {{ if not .user.Verified }} disabled {{ end }}>
        {{ if not .user.Verified }}
          <span id="unconfirmed">
            You have not yet confirmed your e-mail address.
            <button id="resend-button">Resend verification</button>
          </span>
          <span id="reverified" style="display: none">
            Check your e-mail for a verification message from Outlived.
          </span>
        {{ end }}
        <input type="hidden" id="csrf" name="csrf" value="{{ .csrf }}"></input>
      </div>

      <div id="figures-div" style="display: none">
        <p>
          Today is <span id="todaystr"></span>.
          You were born on <span id="userborn"></span>,
          which was <span id="daysalive"></span> days ago.
        </p>

        <p>You have recently outlived:</p>
        <ul id="figures" class="grid"></ul>
      </div>

    {{ else }}

      <div>
        <form id="login-signup-form" method="POST">
          <input type="hidden" name="csrf" value="{{ .csrf }}"></input>
          <input type="hidden" id="tzname" name="tzname"></input>
          <label for="email">E-mail address</label>
          <input type="email" id="email" name="email"></input>
          <span id="email-value" style="display: none"></span>
          <button id="login-button-1" disabled type="button">Log in</button>
          <button id="signup-button-1" disabled type="button">Sign up</button>
          <div id="password-div" style="display: none">
            <label for="password">Password</label>
            <input type="password" id="password" name="password"></input>
          </div>
          <button id="login-button-2" type="submit" style="display: none" disabled>Log in</button>
          <div id="datepicker-div" style="display: none">
            <label for="datepicker">Birthdate</label>
            <input type="text" id="datepicker" name="born" placeholder="yyyy-mm-dd"></input>
          </div>
          <button id="signup-button-2" type="submit" style="display: none" disabled>Sign up</button>
          <button id="cancel-button" style="display: none" type="button">Cancel</button>
        </form>
      </div>

      <div id="figures-div" style="display: none">
        <p>Today is <span id="todaystr"></span>. Died on this date:</p>
        <ul id="figures" class="grid"></ul>
      </div>

    {{ end }}

  </body>
</html>
`
